FORMS += templatewidget.ui
HEADERS += template.h
SOURCES += template.cpp main.cpp
RESOURCES += template.qrc
TEMPLATE = app
CONFIG += release warn_on thread qt
TARGET = template
QT += network
RC_FILE = template.rc
